# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: static_model 1.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "static_model"
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Aaron Quint"]
  s.date = "2015-03-06"
  s.description = "StaticModel provides a Base class much like ActiveRecord which supports reading from a YAML file and basic associations to ActiveRecord"
  s.email = "aaron@quirkey.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Appraisals",
    "Gemfile",
    "History.txt",
    "License.txt",
    "README.rdoc",
    "Rakefile",
    "generators/static_model/USAGE",
    "generators/static_model/static_model_generator.rb",
    "generators/static_model/templates/model.rb.erb",
    "generators/static_model/templates/models.yml.erb",
    "index.html",
    "lib/static_model.rb",
    "lib/static_model/active_record.rb",
    "lib/static_model/active_support.rb",
    "lib/static_model/associations.rb",
    "lib/static_model/base.rb",
    "lib/static_model/comparable.rb",
    "lib/static_model/errors.rb",
    "lib/static_model/rails.rb",
    "lib/static_model/scope.rb",
    "static_model.gemspec",
    "test/associations_test.rb",
    "test/data/authors.yml",
    "test/data/books.yml",
    "test/data/empty.yml",
    "test/data/pages.yml",
    "test/data/projects.yml",
    "test/data/publishers.yml",
    "test/data/stores.yml",
    "test/generator_helper.rb",
    "test/generator_test.rb",
    "test/helper.rb",
    "test/scope_test.rb",
    "test/static_model_test.rb"
  ]
  s.homepage = "http://github.com/quirkey/static_model"
  s.rubyforge_project = "quirkey"
  s.rubygems_version = "2.2.2"
  s.summary = "ActiveRecord like functionalities for reading from YAML with a simple class implementation"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<appraisal>, [">= 1.0.2", "~> 1.0"])
      s.add_development_dependency(%q<minitest>, ["~> 5.5"])
      s.add_development_dependency(%q<mocha>, [">= 1.1.0", "~> 1.1"])
      s.add_development_dependency(%q<rubigen>, [">= 1.5.7"])
      s.add_development_dependency(%q<shoulda-context>, ["~> 1.2"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<appraisal>, [">= 1.0.2", "~> 1.0"])
      s.add_dependency(%q<minitest>, ["~> 5.5"])
      s.add_dependency(%q<mocha>, [">= 1.1.0", "~> 1.1"])
      s.add_dependency(%q<rubigen>, [">= 1.5.7"])
      s.add_dependency(%q<shoulda-context>, ["~> 1.2"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<appraisal>, [">= 1.0.2", "~> 1.0"])
    s.add_dependency(%q<minitest>, ["~> 5.5"])
    s.add_dependency(%q<mocha>, [">= 1.1.0", "~> 1.1"])
    s.add_dependency(%q<rubigen>, [">= 1.5.7"])
    s.add_dependency(%q<shoulda-context>, ["~> 1.2"])
  end
end

